### PR TITLE
Preact [WIP]

### PR DESCRIPTION
**Pull request by btzr-io**
## Changes
- Port website to preact.  https://github.com/workhorsy/comic_book_reader/issues/107
- Simple redesign.

## Done
- [x] Contributors. https://github.com/workhorsy/comic_book_reader/pull/113#issuecomment-377768139
- [x] Menu
- [x] ~Redux~ unistore integration
- [x] Empty states
- [x] Dark / light themes https://github.com/workhorsy/comic_book_reader/issues/102
- [x] Load saved data
- [x] Port / Fix Settings https://github.com/workhorsy/comic_book_reader/issues/110

## Todo
- [ ] Port Reader
- [ ] Port Library

### CODE REVIEW

**Comment by workhorsy** [comment]
Nice! I'll see if I can test this out tonight.

**Comment by workhorsy** [comment]
Testing it now. Looks good.

**Comment by workhorsy** [comment]
You should add yourself to the copyrights.

You could also update the copyright footer. Something like this maybe? I'm not sure what to put on a website copyright footer, when there are multiple copyright holders:
```
Copyright © 2017 - 2018 Comic Book Reader Developers
```

**Comment by btzr-io** [comment]
I think that makes sense, I found a tool to handle contributors ->  [all-contributors-cli](https://github.com/jfmengels/all-contributors-cli)
I'll add it to the repo ^^

**Comment by workhorsy** [comment]
If I pull this into my preact branch, and you make more changes, will it let me merge it again? Or will it close the pull request? I'm not sure how that works. I've never had to pull from the same branch multiple times.

**Comment by btzr-io** [comment]
not sure, but you can merge this PR if you want ,
I think we should make a new PR or branch for the reader / viewer...

**Comment by workhorsy** [comment]
Crossing fingers.

**Pull request merged**
